
version: '3.8'

services:
  app:
    image: be_chat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mydb
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mydb:3306/chat
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network

  mydb:
    image: mysql:8.0
    container_name: mydb
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
      
  
volumes:
  mysql_data:

networks:
  app-network:

